export const exportToJSON = (result: any, filename: string = 'research_results') => {
  const data = {
    metadata: {
      exported_at: new Date().toISOString(),
      topic: result.topic,
      session_id: result.session_id,
    },
    results: {
      papers_analyzed: result.papers,
      graph_statistics: result.graph_stats,
      research_gaps: result.gaps,
      hypothesis: result.hypothesis,
      reasoning: result.reasoning,
    },
  };

  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
  const url = window.URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${filename}_${Date.now()}.json`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  window.URL.revokeObjectURL(url);
};

export const exportToMarkdown = (result: any, filename: string = 'research_report') => {
  const markdown = `# Research Report: ${result.topic}

**Generated:** ${new Date().toLocaleString()}  
**Session ID:** ${result.session_id}

---

## 📊 Overview

- **Papers Analyzed:** ${result.papers || 0}
- **Research Gaps Found:** ${result.gaps || 0}
- **Methods Identified:** ${result.graph_stats?.method_count || 0}
- **Datasets Found:** ${result.graph_stats?.dataset_count || 0}
- **Metrics Tracked:** ${result.graph_stats?.metric_count || 0}

---

## 💡 Research Hypothesis

${result.hypothesis || 'No hypothesis generated'}

---

## 📝 Reasoning

${result.reasoning || 'No reasoning provided'}

---

## 🗺️ Knowledge Graph Statistics

| Category | Count |
|----------|-------|
| Papers | ${result.graph_stats?.paper_count || 0} |
| Authors | ${result.graph_stats?.author_count || 0} |
| Methods | ${result.graph_stats?.method_count || 0} |
| Datasets | ${result.graph_stats?.dataset_count || 0} |
| Metrics | ${result.graph_stats?.metric_count || 0} |
| Relationships | ${result.graph_stats?.relationship_count || 0} |

---

*Report generated by Scientific Pathfinder - AI-Powered Research Gap Discovery*
`;

  const blob = new Blob([markdown], { type: 'text/markdown' });
  const url = window.URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${filename}_${Date.now()}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  window.URL.revokeObjectURL(url);
};

export const copyToClipboard = async (text: string): Promise<boolean> => {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (err) {
    console.error('Failed to copy:', err);
    return false;
  }
};

export const shareResults = (result: any): string => {
  const shareText = `🔬 Research Discovery: ${result.topic}

📊 Found ${result.gaps} research gaps across ${result.papers} papers!

💡 Hypothesis: ${result.hypothesis?.substring(0, 200)}...

Generated by Scientific Pathfinder`;

  return shareText;
};