import { Download, ExternalLink, Network, FileJson, FileText, Share2, Copy, Check } from 'lucide-react';
import { useState, useEffect } from 'react';
import GraphVisualization from './GraphVisualization';

export default function ResultsDisplay({ result, sessionId }: any) {
  const [showGraph, setShowGraph] = useState(false);
  const [showPapers, setShowPapers] = useState(false);
  const [showExportMenu, setShowExportMenu] = useState(false);
  const [copySuccess, setCopySuccess] = useState(false);
  const [notification, setNotification] = useState<string | null>(null);

  // Close export menu when clicking outside
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      const target = event.target as HTMLElement;
      if (showExportMenu && !target.closest('.export-menu-container')) {
        setShowExportMenu(false);
      }
    };

    if (showExportMenu) {
      document.addEventListener('mousedown', handleClickOutside);
      return () => document.removeEventListener('mousedown', handleClickOutside);
    }
  }, [showExportMenu]);

  const showNotification = (message: string) => {
    setNotification(message);
    setTimeout(() => setNotification(null), 3000);
  };

  const handleDownload = () => {
    try {
      console.log('Download button clicked');
      console.log('Result:', result);

      if (!result || (!result.hypothesis && !result.validation_script)) {
        alert('No data available to download');
        return;
      }

      // Create Python script content
      const scriptContent = `"""
Validation Script for Research Hypothesis
Generated by Scientific Pathfinder

Topic: ${result.topic || 'Unknown'}
Generated: ${new Date().toISOString()}
Session ID: ${sessionId || 'N/A'}
"""

# ============================================================================
# RESEARCH HYPOTHESIS
# ============================================================================
"""
${result.hypothesis || 'No hypothesis generated'}
"""

# ============================================================================
# REASONING
# ============================================================================
"""
${result.reasoning || 'No reasoning provided'}
"""

# ============================================================================
# GRAPH STATISTICS
# ============================================================================
# Papers analyzed: ${result.papers || 0}
# Methods found: ${result.graph_stats?.method_count || 0}
# Datasets found: ${result.graph_stats?.dataset_count || 0}
# Metrics tracked: ${result.graph_stats?.metric_count || 0}
# Research gaps identified: ${result.gaps || 0}

# ============================================================================
# IMPLEMENTATION TEMPLATE
# ============================================================================

import torch
import torch.nn as nn
from torch.utils.data import DataLoader
import numpy as np
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def validate_hypothesis():
    """
    Validate the research hypothesis through experiments.
    
    Steps:
    1. Load datasets mentioned in hypothesis
    2. Implement or load the methods
    3. Run experiments
    4. Collect metrics
    5. Analyze results
    """
    print("Starting validation experiments...")
    print("Topic: ${result.topic || 'Unknown'}")
    
    # TODO: Implement your validation experiments here
    # TODO: Use the datasets and methods mentioned in the hypothesis
    # TODO: Compare with baseline approaches
    # TODO: Document your findings
    
    pass

if __name__ == "__main__":
    print("=" * 60)
    print("Scientific Pathfinder - Validation Script")
    print("=" * 60)
    validate_hypothesis()
    print("=" * 60)
`;

      console.log('Script content created, length:', scriptContent.length);

      // Create and trigger download
      const blob = new Blob([scriptContent], { type: 'text/plain;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      const filename = `validation_${(result.topic || 'research').replace(/[^a-z0-9]/gi, '_').toLowerCase()}_${Date.now()}.py`;
      link.download = filename;
      
      console.log('Triggering download:', filename);
      
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
      
      console.log('Download triggered successfully');
      showNotification('✓ Script downloaded successfully!');
    } catch (error) {
      console.error('Download error:', error);
      alert(`Download failed: ${error}`);
    }
  };

  const handleViewGraph = () => {
    console.log('Opening graph visualization');
    setShowGraph(true);
  };

  const handleViewPapers = () => {
    console.log('Opening papers list');
    setShowPapers(true);
  };

  const handleExportJSON = () => {
    try {
      console.log('Exporting as JSON');
      
      const data = {
        metadata: {
          exported_at: new Date().toISOString(),
          topic: result.topic,
          session_id: sessionId,
        },
        results: {
          papers_analyzed: result.papers,
          graph_statistics: result.graph_stats,
          research_gaps: result.gaps,
          hypothesis: result.hypothesis,
          reasoning: result.reasoning,
        },
      };

      const jsonString = JSON.stringify(data, null, 2);
      const blob = new Blob([jsonString], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `research_results_${Date.now()}.json`;
      
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
      
      setShowExportMenu(false);
      showNotification('✓ JSON exported successfully!');
      console.log('JSON export complete');
    } catch (error) {
      console.error('JSON export error:', error);
      alert(`Export failed: ${error}`);
    }
  };

  const handleExportMarkdown = () => {
    try {
      console.log('Exporting as Markdown');
      
      const markdown = `# Research Report: ${result.topic || 'Unknown'}

**Generated:** ${new Date().toLocaleString()}  
**Session ID:** ${sessionId || 'N/A'}

---

## 📊 Overview

- **Papers Analyzed:** ${result.papers || 0}
- **Research Gaps Found:** ${result.gaps || 0}
- **Methods Identified:** ${result.graph_stats?.method_count || 0}
- **Datasets Found:** ${result.graph_stats?.dataset_count || 0}
- **Metrics Tracked:** ${result.graph_stats?.metric_count || 0}

---

## 💡 Research Hypothesis

${result.hypothesis || 'No hypothesis generated'}

---

## 📝 Reasoning

${result.reasoning || 'No reasoning provided'}

---

## 🗺️ Knowledge Graph Statistics

| Category | Count |
|----------|-------|
| Papers | ${result.graph_stats?.paper_count || 0} |
| Authors | ${result.graph_stats?.author_count || 0} |
| Methods | ${result.graph_stats?.method_count || 0} |
| Datasets | ${result.graph_stats?.dataset_count || 0} |
| Metrics | ${result.graph_stats?.metric_count || 0} |
| Relationships | ${result.graph_stats?.relationship_count || 0} |

---

*Report generated by Scientific Pathfinder - AI-Powered Research Gap Discovery*
`;

      const blob = new Blob([markdown], { type: 'text/markdown' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `research_report_${Date.now()}.md`;
      
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
      
      setShowExportMenu(false);
      showNotification('✓ Markdown report downloaded!');
      console.log('Markdown export complete');
    } catch (error) {
      console.error('Markdown export error:', error);
      alert(`Export failed: ${error}`);
    }
  };

  const handleCopyHypothesis = async () => {
    try {
      console.log('Copying hypothesis to clipboard');
      
      if (!result.hypothesis) {
        alert('No hypothesis to copy');
        return;
      }

      const textToCopy = `Research Hypothesis: ${result.topic || 'Unknown'}

${result.hypothesis}

Reasoning:
${result.reasoning || 'No reasoning provided'}

Generated by Scientific Pathfinder`;

      // Try modern clipboard API first
      if (navigator.clipboard && navigator.clipboard.writeText) {
        await navigator.clipboard.writeText(textToCopy);
        console.log('Copied using Clipboard API');
      } else {
        // Fallback for older browsers
        const textarea = document.createElement('textarea');
        textarea.value = textToCopy;
        textarea.style.position = 'fixed';
        textarea.style.opacity = '0';
        document.body.appendChild(textarea);
        textarea.select();
        document.execCommand('copy');
        document.body.removeChild(textarea);
        console.log('Copied using fallback method');
      }

      setCopySuccess(true);
      showNotification('✓ Hypothesis copied to clipboard!');
      setTimeout(() => setCopySuccess(false), 2000);
      setShowExportMenu(false);
    } catch (error) {
      console.error('Copy error:', error);
      alert(`Copy failed: ${error}. Please try selecting and copying manually.`);
    }
  };

  const handleShare = async () => {
    try {
      console.log('Sharing results');
      
      const shareText = `🔬 Research Discovery: ${result.topic || 'Unknown'}

📊 Analyzed ${result.papers || 0} papers and found ${result.gaps || 0} research gaps!

💡 Hypothesis: ${(result.hypothesis || 'No hypothesis').substring(0, 200)}${result.hypothesis?.length > 200 ? '...' : ''}

Generated by Scientific Pathfinder`;

      // Try native share first
      if (navigator.share) {
        await navigator.share({
          title: `Research: ${result.topic}`,
          text: shareText,
        });
        console.log('Shared using native share');
      } else {
        // Fallback to clipboard
        if (navigator.clipboard) {
          await navigator.clipboard.writeText(shareText);
        } else {
          const textarea = document.createElement('textarea');
          textarea.value = shareText;
          textarea.style.position = 'fixed';
          textarea.style.opacity = '0';
          document.body.appendChild(textarea);
          textarea.select();
          document.execCommand('copy');
          document.body.removeChild(textarea);
        }
        console.log('Copied to clipboard as fallback');
        showNotification('✓ Share text copied to clipboard!');
      }
      
      setShowExportMenu(false);
    } catch (error) {
      console.error('Share error:', error);
      // Silent fail for user cancellation
      if (error instanceof Error && error.name !== 'AbortError') {
        alert(`Share failed: ${error}`);
      }
    }
  };

  return (
    <div className="space-y-6">
      {/* Notification Toast */}
      {notification && (
        <div className="fixed top-4 right-4 bg-green-600 text-white px-6 py-3 rounded-lg shadow-lg z-50 animate-fade-in">
          {notification}
        </div>
      )}

      {/* Stats Cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <StatCard
          label="Papers Analyzed"
          value={result.papers || 0}
          icon="📚"
        />
        <StatCard
          label="Methods Found"
          value={result.graph_stats?.method_count || 0}
          icon="🔬"
        />
        <StatCard
          label="Datasets Found"
          value={result.graph_stats?.dataset_count || 0}
          icon="📊"
        />
        <StatCard
          label="Research Gaps"
          value={result.gaps || 0}
          icon="💡"
        />
      </div>

      {/* Hypothesis */}
      <div className="bg-slate-800/50 backdrop-blur-sm rounded-2xl border border-blue-500/20 p-8 relative z-10">
        <h2 className="text-2xl font-bold text-white mb-4 flex items-center gap-2">
          💡 Research Hypothesis
        </h2>
        <div className="prose prose-invert max-w-none">
          <p className="text-blue-100 leading-relaxed whitespace-pre-wrap">
            {result.hypothesis || 'No hypothesis generated'}
          </p>
        </div>

        {result.reasoning && (
          <div className="mt-6 p-4 bg-blue-900/20 rounded-lg">
            <h3 className="text-sm font-semibold text-blue-200 mb-2">
              📝 Reasoning
            </h3>
            <p className="text-sm text-blue-100/80 whitespace-pre-wrap">
              {result.reasoning}
            </p>
          </div>
        )}

        <div className="mt-6 flex gap-3 flex-wrap">
          <button 
            onClick={handleDownload}
            className="flex items-center gap-2 px-6 py-3 bg-green-600 hover:bg-green-700 text-white rounded-lg transition-colors font-medium"
            title="Download Python validation script"
          >
            <Download className="w-4 h-4" />
            Download Script
          </button>
          
          <button 
            onClick={handleViewGraph}
            className="flex items-center gap-2 px-6 py-3 bg-purple-600 hover:bg-purple-700 text-white rounded-lg transition-colors font-medium"
            title="Visualize knowledge graph"
          >
            <Network className="w-4 h-4" />
            Visualize Graph
          </button>
          
          <button 
            onClick={handleViewPapers}
            className="flex items-center gap-2 px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white rounded-lg transition-colors font-medium"
            title="View all analyzed papers"
          >
            <ExternalLink className="w-4 h-4" />
            View Papers
          </button>
          
          {/* Export Menu */}
          <div className="relative export-menu-container">
            <button 
              onClick={() => setShowExportMenu(!showExportMenu)}
              className="flex items-center gap-2 px-6 py-3 bg-slate-700 hover:bg-slate-600 text-white rounded-lg transition-colors font-medium"
              title="Export results in different formats"
            >
              <FileJson className="w-4 h-4" />
              Export
              <span className="text-xs ml-1">▼</span>
            </button>
            
            {showExportMenu && (
              <div className="absolute top-full mt-2 right-0 bg-slate-800 rounded-lg border border-blue-500/20 shadow-xl z-50 min-w-[220px]">
                <button
                  onClick={handleExportJSON}
                  className="w-full flex items-center gap-3 px-4 py-3 hover:bg-slate-700 transition-colors text-left text-white rounded-t-lg"
                >
                  <FileJson className="w-4 h-4 text-blue-400" />
                  <span>Export as JSON</span>
                </button>
                <button
                  onClick={handleExportMarkdown}
                  className="w-full flex items-center gap-3 px-4 py-3 hover:bg-slate-700 transition-colors text-left text-white border-t border-slate-700"
                >
                  <FileText className="w-4 h-4 text-green-400" />
                  <span>Export as Markdown</span>
                </button>
                <button
                  onClick={handleCopyHypothesis}
                  className="w-full flex items-center gap-3 px-4 py-3 hover:bg-slate-700 transition-colors text-left text-white border-t border-slate-700"
                >
                  {copySuccess ? (
                    <>
                      <Check className="w-4 h-4 text-green-400" />
                      <span>Copied!</span>
                    </>
                  ) : (
                    <>
                      <Copy className="w-4 h-4 text-purple-400" />
                      <span>Copy Hypothesis</span>
                    </>
                  )}
                </button>
                <button
                  onClick={handleShare}
                  className="w-full flex items-center gap-3 px-4 py-3 hover:bg-slate-700 transition-colors text-left text-white border-t border-slate-700 rounded-b-lg"
                >
                  <Share2 className="w-4 h-4 text-orange-400" />
                  <span>Share Results</span>
                </button>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Graph Stats Details */}
      {result.graph_stats && (
        <div className="bg-slate-800/50 backdrop-blur-sm rounded-2xl border border-blue-500/20 p-8 relative z-0">
          <h2 className="text-xl font-bold text-white mb-4">
            📊 Knowledge Graph Details
          </h2>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-4 text-sm">
            <div className="text-blue-200">
              <span className="text-slate-400">Papers:</span> <strong>{result.graph_stats.paper_count}</strong>
            </div>
            <div className="text-blue-200">
              <span className="text-slate-400">Authors:</span> <strong>{result.graph_stats.author_count}</strong>
            </div>
            <div className="text-blue-200">
              <span className="text-slate-400">Methods:</span> <strong>{result.graph_stats.method_count}</strong>
            </div>
            <div className="text-blue-200">
              <span className="text-slate-400">Datasets:</span> <strong>{result.graph_stats.dataset_count}</strong>
            </div>
            <div className="text-blue-200">
              <span className="text-slate-400">Metrics:</span> <strong>{result.graph_stats.metric_count}</strong>
            </div>
            <div className="text-blue-200">
              <span className="text-slate-400">Relationships:</span> <strong>{result.graph_stats.relationship_count}</strong>
            </div>
          </div>
        </div>
      )}

      {/* Modals */}
      {showGraph && (
        <GraphVisualization
          sessionId={sessionId}
          onClose={() => setShowGraph(false)}
        />
      )}

      {showPapers && (
        <div className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-slate-900 rounded-2xl border border-blue-500/20 max-w-6xl w-full max-h-[90vh] overflow-hidden flex flex-col">
            <div className="p-6 border-b border-blue-500/20 flex justify-between items-center">
              <h2 className="text-2xl font-bold text-white">📚 Analyzed Papers</h2>
              <button
                onClick={() => setShowPapers(false)}
                className="p-2 hover:bg-slate-800 rounded-lg transition-colors text-slate-400"
              >
                ✕
              </button>
            </div>
            <div className="flex-1 overflow-y-auto p-6">
              {result.papers && result.papers > 0 ? (
                <div className="text-center py-12">
                  <p className="text-slate-400 mb-4">
                    {result.papers} papers were analyzed for this research.
                  </p>
                  <p className="text-sm text-slate-500">
                    Detailed paper information will be available in a future update.
                  </p>
                  <p className="text-sm text-blue-400 mt-4">
                    💡 Tip: Check the Knowledge Graph visualization to see paper relationships.
                  </p>
                </div>
              ) : (
                <div className="text-center py-12">
                  <p className="text-slate-400">No papers to display</p>
                </div>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

function StatCard({ label, value, icon }: any) {
  return (
    <div className="bg-slate-800/50 backdrop-blur-sm rounded-xl border border-blue-500/20 p-6 hover:border-blue-500/40 transition-all">
      <div className="text-3xl mb-2">{icon}</div>
      <div className="text-3xl font-bold text-white">{value}</div>
      <div className="text-sm text-blue-200/70">{label}</div>
    </div>
  );
}